server:
  port: 8089
  #freemarker config
spring:
  freemarker:
    cache: false
    check-template-location: true
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates/s
    expose-spring-macro-helpers: true
  #mybaits config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ocdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
mybatis:
  type-aliases-package: com.online.college
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
